###############################################################################
setxkbmap gb #change to keyboard layout us to gb
export PATH=$HOME/bin:$PATH
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
export PATH=/usr/local/go/bin:$HOME/go/bin:$PATH
